export const LOGIN = "LOGIN";

export const GET_ALL_CLIENTS = "GET_ALL_CLIENTS";
export const CREATE_NEW_CLIENT = "CREATE_NEW_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT_STOCK = "EDIT_PRODUCT_STOCK";
export const EDIT_AUMENTO = "EDIT_AUMENTO";

export const GET_ALL_PEDIDOS = "GET_ALL_PEDIDOS";
export const CREATE_PEDIDO = "CREATE_NEW_PEDIDO";
export const EDIT_PEDIDO = "EDIT_PEDIDO";
export const DELETE_PEDIDO = "DELETE_PEDIDO";

export const GET_ALL_SUBPEDIDOS = "GET_ALL_SUBPEDIDOS";
export const CREATE_SUBPEDIDO = "CREATE_NEW_PEDIDO";
export const EDIT_SUBPEDIDO = "EDIT_SUBPEDIDO";
export const DELETE_SUBPEDIDO = "DELETE_SUBPEDIDO";

export const GET_ALL_APORTESYGASTOS = "GET_ALL_APORTESYGASTOS";
export const CREATE_APORTEYGASTO = "CREATE_APORTEYGASTO";
export const EDIT_APORTEYGASTO = "EDIT_APORTEYGASTO";
export const DELETE_APORTEYGASTO = "DELETE_APORTEYGASTO";
